# This file is a template, and might need editing before it works on your project.
image: golang:latest

variables:
  # Please edit to your GitLab project
  REPO_NAME: gitlab.com/michenriksen/jdam
  PACKAGE_VERSION: "0.1.0"
  DARWIN_AMD64_BINARY: "jdam-darwin-amd64-${CI_COMMIT_TAG}"
  LINUX_AMD64_BINARY: "jdam-linux-amd64-${CI_COMMIT_TAG}"
  WINDOWS_AMD64_BINARY: "jdam-windows-amd64-${CI_COMMIT_TAG}.exe"
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/jdam/${PACKAGE_VERSION}"

stages:
  - test
  - build
  - upload
  - release

format:
  stage: test
  before_script:
    - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
    - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
    - cd $GOPATH/src/$REPO_NAME
  script:
    - go fmt $(go list ./... | grep -v /vendor/ | grep -v /examples/)
    - go vet $(go list ./... | grep -v /vendor/ | grep -v /examples/)

unit:
  stage: test
  before_script:
    - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
    - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
    - cd $GOPATH/src/$REPO_NAME
  script:
    - go test -race $(go list ./... | grep -v /vendor/ | grep -v /examples/)

compile:
  stage: build
  before_script:
    - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
    - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
    - cd $GOPATH/src/$REPO_NAME
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - mkdir $CI_PROJECT_DIR/build
    - GOOS=darwin GOARCH=amd64 go build -o $CI_PROJECT_DIR/build/${DARWIN_AMD64_BINARY} ./cmd/jdam/*
    - GOOS=linux GOARCH=amd64 go build -o $CI_PROJECT_DIR/build/${LINUX_AMD64_BINARY} ./cmd/jdam/*
    - GOOS=windows GOARCH=amd64 go build -o $CI_PROJECT_DIR/build/${WINDOWS_AMD64_BINARY} ./cmd/jdam/*
    - shasum -a 256 $CI_PROJECT_DIR/build/* > $CI_PROJECT_DIR/build/checksums.txt
  artifacts:
    paths:
      - $CI_PROJECT_DIR/build

upload:
  stage: upload
  image: curlimages/curl:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file build/${DARWIN_AMD64_BINARY} ${PACKAGE_REGISTRY_URL}/${DARWIN_AMD64_BINARY}
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file build/${LINUX_AMD64_BINARY} ${PACKAGE_REGISTRY_URL}/${LINUX_AMD64_BINARY}
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file build/${WINDOWS_AMD64_BINARY} ${PACKAGE_REGISTRY_URL}/${WINDOWS_AMD64_BINARY}
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file build/checksums.txt ${PACKAGE_REGISTRY_URL}/checksums.txt

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - |
      release-cli create --name "Release $CI_COMMIT_TAG" --tag-name $CI_COMMIT_TAG \
        --assets-link "{\"name\":\"${DARWIN_AMD64_BINARY}\",\"url\":\"${PACKAGE_REGISTRY_URL}/${DARWIN_AMD64_BINARY}\"}" \
        --assets-link "{\"name\":\"${LINUX_AMD64_BINARY}\",\"url\":\"${PACKAGE_REGISTRY_URL}/${LINUX_AMD64_BINARY}\"}" \
        --assets-link "{\"name\":\"${WINDOWS_AMD64_BINARY}\",\"url\":\"${PACKAGE_REGISTRY_URL}/${WINDOWS_AMD64_BINARY}\"}" \
        --assets-link "{\"name\":\"checksums.txt\",\"url\":\"${PACKAGE_REGISTRY_URL}/checksums.txt\"}"

